// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestBackend.Infrastructure.Persistence;

#nullable disable

namespace QuestBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuestDbContext))]
    [Migration("20260324203104_TeamEnigmaSolved")]
    partial class TeamEnigmaSolved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestBackend.Domain.Admin.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Audit.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiffJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Audit.ConfigSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("config_snapshots", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Config.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswerCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentEnigmaProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentQuestDayStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRoutingProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultAnswerNormalization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnigmaCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("global_settings", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CooldownAppliedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnigmaProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvaluationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("EnigmaProfileId");

                    b.HasIndex("TeamId");

                    b.ToTable("enigma_attempts", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecretCombinationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuccessMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("enigma_profiles", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaRotorDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorOverride")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EnigmaProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionMax")
                        .HasColumnType("integer");

                    b.Property<int>("PositionMin")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("EnigmaProfileId", "DisplayOrder");

                    b.ToTable("enigma_rotor_definitions", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.TeamEnigmaDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnigmaProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("PositionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnigmaProfileId");

                    b.HasIndex("TeamId", "EnigmaProfileId")
                        .IsUnique();

                    b.ToTable("team_enigma_drafts", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.TeamRotorReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SourceQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceQuestionId");

                    b.HasIndex("TagId");

                    b.HasIndex("TeamId", "SourceQuestionId")
                        .IsUnique();

                    b.HasIndex("TeamId", "TagId");

                    b.ToTable("team_rotor_rewards", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Participants.ParticipantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("participant_users", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.QrScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QrCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionMetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResolutionResult")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResolvedQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("QrCodeId");

                    b.HasIndex("ResolvedQuestionId");

                    b.HasIndex("TeamId");

                    b.ToTable("qr_scan_events", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.TeamAnswerAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CooldownAppliedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamQuestionStateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamQuestionStateId");

                    b.ToTable("team_answer_attempts", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.TeamQuestionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstUnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAllowedAnswerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RewardGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnlockedByQrCodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnlockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UnlockedByQrCodeId");

                    b.HasIndex("TeamId", "QuestionId")
                        .IsUnique();

                    b.ToTable("team_question_states", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.QuestDay.QuestDayState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayClosedMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DayCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EndedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreStartMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StartedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayCode")
                        .IsUnique();

                    b.ToTable("quest_day_states", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyRichText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FooterHint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UiMetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AnswerSchema", "QuestBackend.Domain.Questions.Question.AnswerSchema#AnswerSchema", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("AcceptedAnswers")
                                .IsRequired();

                            b1.Property<decimal?>("ExpectedNumericValue");

                            b1.Property<int>("Kind");

                            b1.Property<decimal?>("NumericTolerance");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Normalization", "QuestBackend.Domain.Questions.Question.AnswerSchema#AnswerSchema.Normalization#AnswerNormalizationOptions", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("CollapseInnerWhitespace");

                                    b2.Property<bool>("IgnoreCase");

                                    b2.Property<bool>("RemovePunctuation");

                                    b2.Property<bool>("TrimWhitespace");
                                });

                            b1
                                .ToJson("AnswerSchema")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TagId", "Status");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QrBindingOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QrCodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ScopeProfileId");

                    b.HasIndex("QrCodeId", "IsActive");

                    b.ToTable("qr_binding_overrides", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TagId");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QuestionPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("question_pools", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QuestionPoolEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("PoolId", "Position")
                        .IsUnique();

                    b.HasIndex("PoolId", "QuestionId");

                    b.ToTable("question_pool_entries", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.RoutingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActivatedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("routing_profiles", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.RoutingProfileTagState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RotationOffset")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutingProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivePoolId");

                    b.HasIndex("TagId");

                    b.HasIndex("RoutingProfileId", "TagId")
                        .IsUnique();

                    b.ToTable("routing_profile_tag_states", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Tags.QuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UiMetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("question_tags", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EnigmaSolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnigmaSolvedProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinSecretHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Teams.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantUserId");

                    b.HasIndex("TeamId", "ParticipantUserId", "Status");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaAttempt", b =>
                {
                    b.HasOne("QuestBackend.Domain.Enigma.EnigmaProfile", "EnigmaProfile")
                        .WithMany()
                        .HasForeignKey("EnigmaProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany("EnigmaAttempts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnigmaProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaRotorDefinition", b =>
                {
                    b.HasOne("QuestBackend.Domain.Enigma.EnigmaProfile", "EnigmaProfile")
                        .WithMany("RotorDefinitions")
                        .HasForeignKey("EnigmaProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnigmaProfile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.TeamEnigmaDraft", b =>
                {
                    b.HasOne("QuestBackend.Domain.Enigma.EnigmaProfile", "EnigmaProfile")
                        .WithMany("TeamDrafts")
                        .HasForeignKey("EnigmaProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany("EnigmaDrafts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnigmaProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.TeamRotorReward", b =>
                {
                    b.HasOne("QuestBackend.Domain.Questions.Question", "SourceQuestion")
                        .WithMany()
                        .HasForeignKey("SourceQuestionId");

                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany("RotorRewards")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceQuestion");

                    b.Navigation("Tag");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.QrScanEvent", b =>
                {
                    b.HasOne("QuestBackend.Domain.Routing.QrCode", "QrCode")
                        .WithMany()
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Questions.Question", "ResolvedQuestion")
                        .WithMany()
                        .HasForeignKey("ResolvedQuestionId");

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("QrCode");

                    b.Navigation("ResolvedQuestion");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.TeamAnswerAttempt", b =>
                {
                    b.HasOne("QuestBackend.Domain.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Progress.TeamQuestionState", null)
                        .WithMany("Attempts")
                        .HasForeignKey("TeamQuestionStateId");

                    b.Navigation("Question");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.TeamQuestionState", b =>
                {
                    b.HasOne("QuestBackend.Domain.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany("QuestionStates")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Routing.QrCode", "UnlockedByQrCode")
                        .WithMany()
                        .HasForeignKey("UnlockedByQrCodeId");

                    b.Navigation("Question");

                    b.Navigation("Team");

                    b.Navigation("UnlockedByQrCode");
                });

            modelBuilder.Entity("QuestBackend.Domain.Questions.Question", b =>
                {
                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany("Questions")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QrBindingOverride", b =>
                {
                    b.HasOne("QuestBackend.Domain.Routing.QrCode", "QrCode")
                        .WithMany("Overrides")
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Routing.RoutingProfile", "ScopeProfile")
                        .WithMany()
                        .HasForeignKey("ScopeProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QrCode");

                    b.Navigation("Question");

                    b.Navigation("ScopeProfile");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QrCode", b =>
                {
                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany("QrCodes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QuestionPool", b =>
                {
                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany("Pools")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QuestionPoolEntry", b =>
                {
                    b.HasOne("QuestBackend.Domain.Routing.QuestionPool", "Pool")
                        .WithMany("Entries")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Questions.Question", "Question")
                        .WithMany("PoolEntries")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.RoutingProfileTagState", b =>
                {
                    b.HasOne("QuestBackend.Domain.Routing.QuestionPool", "ActivePool")
                        .WithMany()
                        .HasForeignKey("ActivePoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuestBackend.Domain.Routing.RoutingProfile", "RoutingProfile")
                        .WithMany("TagStates")
                        .HasForeignKey("RoutingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Tags.QuestionTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePool");

                    b.Navigation("RoutingProfile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuestBackend.Domain.Teams.TeamMembership", b =>
                {
                    b.HasOne("QuestBackend.Domain.Participants.ParticipantUser", "ParticipantUser")
                        .WithMany("Memberships")
                        .HasForeignKey("ParticipantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestBackend.Domain.Teams.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParticipantUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuestBackend.Domain.Enigma.EnigmaProfile", b =>
                {
                    b.Navigation("RotorDefinitions");

                    b.Navigation("TeamDrafts");
                });

            modelBuilder.Entity("QuestBackend.Domain.Participants.ParticipantUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("QuestBackend.Domain.Progress.TeamQuestionState", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("QuestBackend.Domain.Questions.Question", b =>
                {
                    b.Navigation("PoolEntries");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QrCode", b =>
                {
                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.QuestionPool", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("QuestBackend.Domain.Routing.RoutingProfile", b =>
                {
                    b.Navigation("TagStates");
                });

            modelBuilder.Entity("QuestBackend.Domain.Tags.QuestionTag", b =>
                {
                    b.Navigation("Pools");

                    b.Navigation("QrCodes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuestBackend.Domain.Teams.Team", b =>
                {
                    b.Navigation("EnigmaAttempts");

                    b.Navigation("EnigmaDrafts");

                    b.Navigation("Memberships");

                    b.Navigation("QuestionStates");

                    b.Navigation("RotorRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
