<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\QuestBackend.Domain\QuestBackend.Domain.csproj" />
    <ProjectReference Include="..\QuestBackend.Contracts\QuestBackend.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
